package ap

const (
	ContentTypeJsonLD  = "application/ld+json"
	ContentTypeProfile = `profile="https://www.w3.org/ns/activitystreams"`

	ContentTypeAppJrdJson = "application/jrd+json"
)

const (
	TypePerson                = "Person"
	TypeNote                  = "Note"
	TypeArticle               = "Article"
	TypeDocument              = "Document"
	TypeImage                 = "Image"
	TypeVideo                 = "Video"
	TypeAudio                 = "Audio"
	TypePage                  = "Page"
	TypeEvent                 = "Event"
	TypePlace                 = "Place"
	TypeMention               = "Mention"
	TypeRelationship          = "Relationship"
	TypeCollection            = "Collection"
	TypeOrderedCollection     = "OrderedCollection"
	TypeCollectionPage        = "CollectionPage"
	TypeOrderedCollectionPage = "OrderedCollectionPage"
	TypeAccept                = "Accept"
	TypeAdd                   = "Add"
	TypeAnnounce              = "Announce"
	TypeArrive                = "Arrive"
	TypeBlock                 = "Block"
	TypeCreate                = "Create"
	TypeDelete                = "Delete"
	TypeDislike               = "Dislike"
	TypeFlag                  = "Flag"
	TypeFollow                = "Follow"
	TypeIgnore                = "Ignore"
	TypeInvite                = "Invite"
	TypeJoin                  = "Join"
	TypeLeave                 = "Leave"
	TypeLike                  = "Like"
	TypeListen                = "Listen"
	TypeMove                  = "Move"
	TypeOffer                 = "Offer"
	TypeQuestion              = "Question"
	TypeReject                = "Reject"
	TypeRead                  = "Read"
	TypeRemove                = "Remove"
	TypeTentativeReject       = "TentativeReject"
	TypeTentativeAccept       = "TentativeAccept"
	TypeTravel                = "Travel"
	TypeUndo                  = "Undo"
	TypeUpdate                = "Update"
	TypeView                  = "View"
	TypeApplication           = "Application"
	TypeGroup                 = "Group"
	TypeOrganization          = "Organization"
	TypeService               = "Service"
)
